### ISSUE TITLE
SVM40 hangs and returns constant values afters some hours of operation

### ISSUE THREAD

**Issue by roviraa** [Sensirion/embedded-svm40#21]
Hi, 
I am trying to get continuous measurements of VOC index, temperature and humidity. My sample rate is 30 seconds. Problem is that every 4 hours or so, data is not refreshed anymore. So far, the only solution I've found to get new values is to disconnect VDD and plug it back. How can I wake up measurments in a better way OR how can I disable this sleeping mode ?
Thanks

**Comment by remyhx** [comment]
Here problem after approx 12 hrs (on nimh 4000mah accupack, lipo is not possible because of project regulations, ac idem). 

Sensirion Svm40 (sgp40), sps30 and scd30 connected to Arduino project by i2c, to measure pm, co2, voc and rh/temp. Tested with a guessed 'survival' time of 20 hrs, after 20,5 it cut off. 

After a simple import in excel, I was surprised to see strange behavior of the svm40(sgp40 voc and shp temp/rh), compared to the others. Pm values rised up after svm40 problem, in fact also worrisome...? (See nb) only the co2 sensor (with build in temp/rh) acted normal. 

My first thought is a voltage/current drop, but expected that later. Or a misdetection of 'bad behavior' of one of the sensors and a missing cut off... 

I'm running a 24hrs check connected to the mains now...


NB: the co2 drop is related to an opened window. Maybe the sudden rise of PM too.. (next to traffic point in city)

![image](https://user-images.githubusercontent.com/74878989/101998923-e9053580-3cd7-11eb-83cb-4e69bf2ed1ca.png)

**Comment by remyhx** [comment]
![Uploading 101998927...]

**Comment by remyhx** [comment]
![image](https://user-images.githubusercontent.com/74878989/101998933-089c5e00-3cd8-11eb-81e4-afd359e7ad5b.png)

**Comment by remyhx** [comment]
![image](https://user-images.githubusercontent.com/74878989/101998939-105c0280-3cd8-11eb-9ae6-87e975ff55b6.png)

**Comment by remyhx** [comment]
![image](https://user-images.githubusercontent.com/74878989/101998942-16ea7a00-3cd8-11eb-8119-a210245daa6e.png)

**Comment by remyhx** [comment]
> Hi, 
> 
> I am trying to get continuous measurements of VOC index, temperature and humidity. My sample rate is 30 seconds. Problem is that every 4 hours or so, data is not refreshed anymore. So far, the only solution I've found to get new values is to disconnect VDD and plug it back. How can I wake up measurments in a better way OR how can I disable this sleeping mode ?
> 
> Thanks

Now. After a night testing with the project connected to the mains the same happened after 4,5 hours now.. 

This excludes the battery. The data is still red, but not updated anymore.. Will wait for the Sensirion reply. 

![image](https://user-images.githubusercontent.com/74878989/102021417-fc6bdb80-3d7f-11eb-94c4-4d2bd322e016.png)

**Comment by remyhx** [comment]
![image](https://user-images.githubusercontent.com/74878989/102021429-0b528e00-3d80-11eb-9003-c86af5ac61d1.png)

**Comment by remyhx** [comment]
![image](https://user-images.githubusercontent.com/74878989/102021438-17d6e680-3d80-11eb-940d-db3fa2103f77.png)

**Comment by roviraa** [comment]
Thanks @remyhx for your replies. 
I made new measurements during the weekend and it has lasted a bit more than 30 hours this time. I have added a kind of "wake up" function but I am not sure if that helped. 

```cpp
void Recover() {
  int16_t err;

  err = svm40_stop_measurement();
  if (err) {
    Particle.publish("error", String("Error stopping measurement: ") + String(err), PRIVATE);
    delay(10000);
  }
  SVM40_COMMS.begin();
  err = svm40_start_continuous_measurement();
  if (err) {
    Particle.publish("error", String("Error stopping measurement: ") + String(err), PRIVATE);
    delay(10000);
  }
  else {
    Particle.publish("restart", "Measurement successfully restarted", PRIVATE);
  }
}
```
Here are my measurements :

![2020-12-14_07h59_20](https://user-images.githubusercontent.com/56686777/102050191-a0866e80-3de2-11eb-8ac0-034f583063ac.png)

**Comment by remyhx** [comment]
One question: how do you connect to the svm40? My partner tried a couple of tests by using the sensor with the usb/uart cable, i connect by i2c.

**Comment by roviraa** [comment]
> One question: how do you connect to the svm40? My partner tried a couple of tests by using the sensor with the usb/uart cable, i connect by i2c.

I am also connected by i2c but using a Particle Argon. You right, I will try with usb/uart cable to see if it behaves similarly

**Comment by rnestler** [comment]
@roviraa @remyhx It seems to be an issue in the SVM40 firmware regarding to error handling during communication with the SGP40 sensor.
It only occurs when the SVM40 is used with the I2C interface and not with the UART interface. We'll try to have a firmware hotfix ready soon.

The firmware of the SVM40 can be upgraded by connecting it via UART and using our Python driver, see https://sensirion.github.io/python-shdlc-svm40/firmware_update.html

I'll post full instructions how to perform the firmware upgrade once the fix is released.

**Comment by rnestler** [comment]
Here is a zip with the SVM-40 2.2 Firmware and a small Python script to upgrade the firmware:  
[svm40-firmware-upgrade.zip](https://github.com/Sensirion/embedded-svm40/files/5694758/svm40-firmware-upgrade.zip)

I tested it on Ubuntu 20.04 with Python 3.8, but it should also work on Windows and other Linux distributions.

Please let me know if this works for you or if you have any problems.

A more official way to upgrade the firmware will follow.

**Comment by roviraa** [comment]
> Here is a zip with the SVM-40 2.2 Firmware and a small Python script to upgrade the firmware:
> [svm40-firmware-upgrade.zip](https://github.com/Sensirion/embedded-svm40/files/5695885/svm40-firmware-upgrade.zip)
> 
> I tested it on Ubuntu 20.04 with Python 3.8, but it should also work on Windows and other Linux distributions.
> 
> Please let me know if this works for you or if you have any problems.
> 
> A more official way to upgrade the firmware will follow.

Hi @rnestler, I've updated the SVM40 firmware using linux :
![2020-12-16_16h01_11](https://user-images.githubusercontent.com/56686777/102453009-aaef7500-403b-11eb-9a10-6f9450c18ce6.png)

It has been running for 16 hours so far with no issues to report. Data keeps evolving so far.
I will let you know if the situation change. Thanks

**Comment by rnestler** [comment]
Happy new year everyone :slightly_smiling_face: 

Since this is fixed with the new firmware version and in the meantime [Sensirion ControlCenter](https://www.sensirion.com/en/controlcenter/) has added support for upgrading the firmware as well I think we can close this issue.

I will add a note to the README and add a check to the example.
