### ISSUE TITLE
Arduino Nano 33 IoT "SVM40 sensor probing failed"

### ISSUE THREAD

**Issue by lidavi-eth** [Sensirion/embedded-svm40#27]
Hi,

so I was following the steps described in README-ARDUINO.rst and I managed to do everything according to the guide.
But when I open the serial monitor, it only gives me the message "SVM40 sensor probing failed".
![image_2021_03_21T16_13_26_156Z](https://user-images.githubusercontent.com/81231413/112136070-ca63e400-8bce-11eb-8d57-f793622fb053.png)

I used this board layout from the Arduino website (https://store.arduino.cc/arduino-nano-33-iot) under the tab DOCUMENTATION:
![Screenshot_3](https://user-images.githubusercontent.com/81231413/112136440-3e05f100-8bcf-11eb-92fa-d50a77a2989c.png)

**Comment by psachs** [comment]
Hi, for arduino please use the dedicated arduino repository instead of the generic embedded driver

 https://github.com/Sensirion/arduino-i2c-svm40

If you have a development kit including the jumper wires, connect them as follows:
Red => 5V
Black => Ground
Green => SDA (A4)
Yellow => SCL (A5)
SEL => Ground (for I2C)

Find attached a picture of my setup.

If you have any further issues, please post them on the SVM40 Arduino repository I mentioned above

![svm40-arduino-nano](https://user-images.githubusercontent.com/864231/112339630-222e4800-8cc0-11eb-87b7-782e84cdcfd9.jpg)
